// <auto-generated />
using System;
using FoodOrderAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOrderAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623085943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("FoodOrderAPI.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("FoodOrderAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodOrderAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FoodOrderAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Burgers",
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "شريحة لحم بقري عصيرية مع خس طازج، طماطم، جبنة، وصلصتنا الخاصة.",
                            DescriptionEn = "Juicy beef patty with fresh lettuce, tomato, cheese, and our special house sauce.",
                            ImageUrl = "/images/burger.png",
                            IsAvailable = true,
                            NameAr = "برجر لحم كلاسيك",
                            NameEn = "Classic Beef Burger",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            Id = 2,
                            Category = "Burgers",
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "شريحتان من اللحم البقري، لحم بقري مقدد مقرمش، جبنة شيدر مضاعفة، مخلل، وصلصة باربكيو.",
                            DescriptionEn = "Two beef patties, crispy beef bacon, double cheddar cheese, pickles, and smoky BBQ sauce.",
                            ImageUrl = "/images/burger.png",
                            IsAvailable = true,
                            NameAr = "دبل باكون تشيز برجر",
                            NameEn = "Double Bacon Cheeseburger",
                            Price = 11.99
                        },
                        new
                        {
                            Id = 3,
                            Category = "Burgers",
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "صدر دجاج مقرمش حار، شريحة جبنة ذائبة، خس مبشور، ومايونيز حار.",
                            DescriptionEn = "Crispy spicy chicken breast fillet, melting cheese slice, shredded lettuce, and spicy mayo.",
                            ImageUrl = "/images/burger.png",
                            IsAvailable = true,
                            NameAr = "برجر دجاج مقرمش حار",
                            NameEn = "Spicy Crispy Chicken Burger",
                            Price = 9.4900000000000002
                        },
                        new
                        {
                            Id = 4,
                            Category = "Pizza",
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "بسيطة ولذيذة مع صلصة الطماطم الكلاسيكية، جبنة الموزاريلا الطازجة، وأوراق الريحان الطازجة.",
                            DescriptionEn = "Simple and delicious with classic tomato sauce, fresh mozzarella cheese, and fresh basil leaves.",
                            ImageUrl = "/images/pizza.png",
                            IsAvailable = true,
                            NameAr = "بيتزا مارجريتا",
                            NameEn = "Margherita Pizza",
                            Price = 10.99
                        },
                        new
                        {
                            Id = 5,
                            Category = "Pizza",
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "محملة بسخاء بشرائح البيبيروني، جبنة الموزاريلا، والأعشاب الإيطالية.",
                            DescriptionEn = "Generously loaded with sliced pepperoni, mozzarella cheese, and Italian herbs.",
                            ImageUrl = "/images/pizza.png",
                            IsAvailable = true,
                            NameAr = "بيتزا بيبيروني",
                            NameEn = "Pepperoni Feast Pizza",
                            Price = 12.99
                        },
                        new
                        {
                            Id = 6,
                            Category = "Pizza",
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "شرائح دجاج مشوية، بصل أحمر، موزاريلا، كزبرة، وصلصة باربكيو حلوة مدخنة.",
                            DescriptionEn = "Grilled chicken slices, red onions, mozzarella, cilantro, and sweet smoky BBQ sauce.",
                            ImageUrl = "/images/pizza.png",
                            IsAvailable = true,
                            NameAr = "بيتزا الدجاج بالباربكيو",
                            NameEn = "BBQ Chicken Pizza",
                            Price = 13.49
                        },
                        new
                        {
                            Id = 7,
                            Category = "Drinks",
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "علبة كوكا كولا مثلجة تقدم مع ثلج وشريحة ليمون.",
                            DescriptionEn = "Chilled Coca Cola can served with ice and lemon slice.",
                            ImageUrl = "/images/drink.png",
                            IsAvailable = true,
                            NameAr = "علبة كوكا كولا",
                            NameEn = "Coca Cola Can",
                            Price = 1.99
                        },
                        new
                        {
                            Id = 8,
                            Category = "Drinks",
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "عصير برتقال طبيعي معصور طازجاً ١٠٠٪.",
                            DescriptionEn = "100% natural freshly squeezed orange juice.",
                            ImageUrl = "/images/drink.png",
                            IsAvailable = true,
                            NameAr = "عصير برتقال طازج",
                            NameEn = "Fresh Orange Juice",
                            Price = 3.4900000000000002
                        },
                        new
                        {
                            Id = 9,
                            Category = "Drinks",
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "كوكتيل منعش مع مياه فوارة، أوراق نعناع طازجة، عصير ليمون، وسكر القصب.",
                            DescriptionEn = "Refreshing cocktail with sparkling water, fresh mint leaves, lime juice, and cane sugar.",
                            ImageUrl = "/images/drink.png",
                            IsAvailable = true,
                            NameAr = "موخيتو ليمون ونعناع",
                            NameEn = "Mojito Lime & Mint",
                            Price = 4.4900000000000002
                        },
                        new
                        {
                            Id = 10,
                            Category = "Desserts",
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "كيك شوكولاتة دافئ مع مركز شوكولاتة سائل، يقدم مع بولا آيس كريم فانيليا.",
                            DescriptionEn = "Warm chocolate cake with a molten liquid chocolate center, served with scoop of vanilla ice cream.",
                            ImageUrl = "/images/dessert.png",
                            IsAvailable = true,
                            NameAr = "مولتن كيك الشوكولاتة",
                            NameEn = "Chocolate Lava Cake",
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            Id = 11,
                            Category = "Desserts",
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "تشيز كيك غني كلاسيكي مع طبقة بسكويت بالزبدة وصلصة الفراولة الحلوة.",
                            DescriptionEn = "Classic rich cheesecake with a buttery graham cracker crust and sweet strawberry syrup.",
                            ImageUrl = "/images/dessert.png",
                            IsAvailable = true,
                            NameAr = "تشيز كيك نيويورك",
                            NameEn = "New York Cheesecake",
                            Price = 6.4900000000000002
                        });
                });

            modelBuilder.Entity("FoodOrderAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@foodhub.com",
                            FullName = "App Administrator",
                            PasswordHash = "$2a$12$Kk.zX6/pBw56.gJzN6mFSeFmC3w99qH9N634N",
                            Role = 1
                        });
                });

            modelBuilder.Entity("FoodOrderAPI.Models.CartItem", b =>
                {
                    b.HasOne("FoodOrderAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodOrderAPI.Models.Order", b =>
                {
                    b.HasOne("FoodOrderAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodOrderAPI.Models.OrderItem", b =>
                {
                    b.HasOne("FoodOrderAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodOrderAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
